name: Build and deploy Github Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build & deploy
    - name: Deploy Zola
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        PAGES_BRANCH: gh-pages
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
